## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
diabetes = datasets.load_boston()

In [110]:
#LinearRregression
x_train, x_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target,test_size = 0.1)
lm = linear_model.LinearRegression()
lm.fit(x_train, y_train)
y_pred = lm.predict(x_test)
lm.coef_

array([-1.15440934e-01,  5.28138251e-02,  2.51029461e-02,  2.15697708e+00,
       -1.84532154e+01,  3.52887262e+00, -6.14282202e-03, -1.64528933e+00,
        3.23664586e-01, -1.29569933e-02, -9.62027933e-01,  8.97013888e-03,
       -5.24240407e-01])

In [111]:
mean_squared_error(y_test, y_pred)

24.259561924668777

In [112]:
#Lasso
lm_La = linear_model.Lasso(alpha=1.0)
lm_La.fit(x_train, y_train)
y_pred = lm_La.predict(x_test)
lm_La.coef_

array([-0.07038515,  0.05985507, -0.        ,  0.        , -0.        ,
        0.64496775,  0.0169313 , -0.74619609,  0.27300279, -0.01582556,
       -0.7046086 ,  0.00747827, -0.76360474])

In [113]:
mean_squared_error(y_test, y_pred)

33.591564296874715

In [114]:
#Ridge
lm_Rd = linear_model.Ridge(alpha=1.0)
lm_Rd.fit(x_train, y_train)
y_pred = lm_Rd.predict(x_test)
lm_Rd.coef_

array([-1.10495632e-01,  5.45311064e-02, -7.92967629e-03,  2.08315020e+00,
       -1.05942404e+01,  3.55529227e+00, -1.23176634e-02, -1.51868603e+00,
        3.06019338e-01, -1.36963266e-02, -8.72159878e-01,  9.38050251e-03,
       -5.36008744e-01])

In [115]:
mean_squared_error(y_test, y_pred)

24.19519307939887